### ISSUE TITLE
Why have you forked stop?

### ISSUE THREAD

**Issue by ForbesLindesay** [pugjs/pug-www#2]
Why have you forked stop?  Can you contribute your changes to https://github.com/ForbesLindesay/stop

**Comment by TimothyGu** [comment]
Just to make modifying it easier. I do eventually want to send pull requests and such, but I wanted to make sure it works properly before doing so. The same applies to react-code-mirror.

**Comment by TimothyGu** [comment]
Pull requests submitted for both repos.
