### ISSUE TITLE
Translation in french

### ISSUE THREAD

**Issue by kylekatarnls** [pugjs/pug-www#57]
Hi, I had to translate most of pugjs documentations contents in French for our PHP port documentation https://phug-lang.com

So now, I could easily translate your whole documentation if you set-up for me the pug-fr repository.

You can rely on my level in French, it's my mother tongue and I master it well.

**Comment by TimothyGu** [comment]
Repo created! https://github.com/pugjs/pug-fr

Invited you to collaborate in that repo (https://github.com/pugjs/pug-fr/invitations).
