### ISSUE TITLE
Extends page has no code content.

### ISSUE THREAD

**Issue by neilsoult** [pugjs/pug-www#8]
![screen shot 2016-09-06 at 3 24 25 pm](https://cloud.githubusercontent.com/assets/5273521/18293198/32578af8-7446-11e6-937d-5c7908292d67.png)

Chrome Version 52.0.2743.116 (64-bit)
OSX 10.11.6

**Comment by TimothyGu** [comment]
Oops, sorry about that. Should be fixed as soon as [Travis](https://travis-ci.org/pugjs/pug-www/builds/158141597) finishes.
